<a href="https://colab.research.google.com/github/danielbrodev/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.2

In [ ]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford",'Tesla','Ford','Ferrari'],
  'passings': [3, 7, 2,6,9,4]
}

df = pd.DataFrame(mydataset)

print(df)

      cars  passings
0      BMW         3
1    Volvo         7
2     Ford         2
3    Tesla         6
4     Ford         9
5  Ferrari         4

In [ ]:
df.head() #default 5 rows

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2
3  Tesla         6
4   Ford         9

In [ ]:
df.tail() # default 5 rows

      cars  passings
1    Volvo         7
2     Ford         2
3    Tesla         6
4     Ford         9
5  Ferrari         4

In [ ]:
df.shape

(6, 2)

In [ ]:
df.columns

Index(['cars', 'passings'], dtype='object')

In [ ]:
df.dtypes

cars        object
passings     int64
dtype: object

In [ ]:
df.describe() # numerical columns only

       passings
count  6.000000
mean   5.166667
std    2.639444
min    2.000000
25%    3.250000
50%    5.000000
75%    6.750000
max    9.000000

In [ ]:
df.iloc[2:]

      cars  passings
2     Ford         2
3    Tesla         6
4     Ford         9
5  Ferrari         4

In [ ]:
df.loc[2:5,"cars"]

2       Ford
3      Tesla
4       Ford
5    Ferrari
Name: cars, dtype: object

In [ ]:
print(df)

      cars  passings
0      BMW         3
1    Volvo         7
2     Ford         2
3    Tesla         6
4     Ford         9
5  Ferrari         4

In [ ]:
df[df["cars"] == "Tesla"]

    cars  passings
3  Tesla         6

In [ ]:
# df.mean(numeric_only=True)
# df["cars"].mean()

In [ ]:
df.sum()

cars        BMWVolvoFordTeslaFordFerrari
passings                              31
dtype: object

In [ ]:
df.min()

cars        BMW
passings      2
dtype: object

In [ ]:
df.max()

cars        Volvo
passings        9
dtype: object

In [ ]:
df.median(numeric_only=True)

passings    5.0
dtype: float64

In [ ]:
df.count()

cars        6
passings    6
dtype: int64

In [ ]:
df.std(numeric_only=True)

passings    2.639444
dtype: float64

In [ ]:
data_with_missing = {
    "cars":["BMW","Volvo",None,"Tesla","Ferrari",None,"Ford"],
    "counts":[3,7,None,8,1,9,None]
}
df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [ ]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [ ]:
df_missing.dropna(subset=['cars'])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [ ]:
df_missing.fillna(0)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2        0     0.0
3    Tesla     8.0
4  Ferrari     1.0
5        0     9.0
6     Ford     0.0

In [99]:
df = pd.read_excel("output.xlsx")

df.head(100)

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [97]:
df.to_excel("output.xlsx")

In [100]:
# Series => 1D
cars = pd.Series(["BMW","Tesla","Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [104]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']